[package]
name = "larch"
version = "0.1.0"
edition = "2021"
liscen = "MIT"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive"] }
enum_dispatch = "0.3.13"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
